### ISSUE TITLE
Delete user account doesn't work

### ISSUE THREAD

**Issue by PulsarFX** [go-vikunja/api#83] opened 2023-09-10 20:43 UTC
### Description

When trying to delete the own user account, a confirm mail is sent, with the hint: 
"... we will schedule the deletion of your account in three days and send you another email until then." 

Then I get an (annoying) email each day, but something is messed up:
It says: 3, 2, 2, 1, 1, 1, 1 days left...
![grafik](https://github.com/go-vikunja/api/assets/4960210/fd5867c3-c852-45fd-8992-3154f6419109)

After 4 days, I can still login and get this banner warning:
"Wir werden deinen Vikunja-Account am 7. Sep. 2023 10:28:08 (vor 4 Tagen) löschen"  
(it says, account will be deleted 4 days ago)

I am using docker compose.

### Vikunja Frontend Version

0.21.0

### Vikunja API Version

0.21.0

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment] 2023-09-13 12:38
In your database, what is the result of the following query?

```sql
select id, deletion_scheduled_at, deletion_last_reminder_sent from users where username = '<your username>';
```

**Comment by PulsarFX** [comment] 2023-09-14 20:59
this gives me:
```
"deletion_scheduled_at":         '2023-09-07 08:28:08',
"deletion_last_reminder_sent":   '2023-09-14 09:00:00'
```

**Comment by mgmorcos** [comment] 2023-09-17 21:01
👍 Encountered this issue as well

**Comment by kolaente** [comment] 2023-09-27 16:05
Does your account have a default project set?

**Comment by PulsarFX** [comment] 2023-09-29 11:14
I created this user to see what a new user can see in vikunja. I did not configure any setting.
When I go to settings it says "Inbox" for default project

**Comment by kolaente** [comment] 2023-09-29 17:21
I guess that's the cause of the issue. It will not allow you to remove the project when it is set as the default project of a user. This fails to take into account the deletion of a user will also delete all of their projects.

The problem is already kind of fixed in the next version (current unstable) when deleting users via the CLI, I'll take a look to make sure this also works when a user self-requests the deletion of their account.

**Comment by kolaente** [comment] 2023-09-29 19:34
Checked again, this should not be a problem anymore. Please check with the last unstable build to see if the problem went away.

**Closed** 2023-09-29 19:34 UTC
Labels: bug
