### ISSUE TITLE
Saved filter with assignees doesn't work since 0.22.1

### ISSUE THREAD

**Issue by mvalois** [go-vikunja/api#109] opened 2024-01-29 08:57 UTC
### Description

I had a saved filter that shows me every tasks where I am assigned on. For that I just created a saved filter with assignees "myusername". It worked well on 0.22.0 until I upgraded to 0.22.1.

Since then the API call to the endpoint '/projects/-5/tasks' returns an empty list (and therefore the board is empty too).
If I filter by another field like label, it works as expected. I tried filtering with other usernames and still didn't get any result.

I observe the same behaviour using Firefox or the desktop app.

### Vikunja Frontend Version

0.22.1

### Vikunja API Version

0.22.1

### Browser and version

Firefox 

### Can you reproduce the bug on the Vikunja demo site?

No

### Screenshots

![Screenshot 2024-01-29 at 09-56-27 Current Tasks Vikunja](https://github.com/go-vikunja/api/assets/30313678/814c4985-b9d1-4173-bcd7-06d5739adb20)
![Screenshot 2024-01-29 at 09-56-38 Mes projets Vikunja](https://github.com/go-vikunja/api/assets/30313678/e8081107-5fbd-4faa-86c6-f221b6237e77)

**Comment by kolaente** [comment] 2024-01-29 20:26
I'm unable to reproduce this with the latest unstable build.

Does your filter only contain the assignee? Or other attributes as well? Does it work if you recreate the same filter?

**Comment by mvalois** [comment] 2024-01-30 08:49
The filter only contains the assignee. It does not work if I recreate the same filter.
BTW we have migrated users from local auth to OpenID auth so we may have messed up with something. We only changed `issuer` from `local` to our SSO URL.

**Comment by kolaente** [comment] 2024-01-30 10:00
Can you check the actual filter json? Does it contain the correct username? Does it work if you filter on a project (not with a saved filter)

**Comment by kolaente** [comment] 2024-01-30 10:17
And your username is `mvalois` on the Vikunja instance? And it is empty with all usernames?

**Comment by mvalois** [comment] 2024-01-30 11:13
Yes my username is `mvalois` : 
```
MariaDB [vikunja]> select username from users where username='mvalois';
+----------+
| username |
+----------+
| mvalois  |
+----------+
```

Yes it is empty with every username.

**Comment by kolaente** [comment] 2024-01-31 19:53
It's not really reproducible for me. Can you [enable database logging](https://vikunja.io/docs/config-options/#database-2) and share the queries being done when you access the filter?

**Comment by kolaente** [comment] 2024-02-01 15:20
> I also noticed there is an error in the stderr when accessing the filter:

That probably is the cause.
I've just pushed a change (8efdc96d02b89a5f2fabb666ab62a9202a00cbfc) which adds more logging to that case. Please pull the next unstable build (ready in ~45min) and check the log message again.

**Comment by mvalois** [comment] 2024-02-01 20:56
here is the log 
```
2024-02-01T21:54:31.020532921+01:00: ERROR      ▶ models/convertFilterValues 133 Unknown search type for value [mvalois] of type []string
```

**Comment by mvalois** [comment] 2024-02-02 12:53
Weird, I reimported the database (mysql) in my other test instance and the filter is working as expected.

**Comment by kolaente** [comment] 2024-02-05 21:09
Should be fixed in https://github.com/go-vikunja/api/commit/b95b92a23add9942c5c0425322f692b4304831ff. Please check with the next unstable build (ready in ~45min) if the problem went away.

**Closed** 2024-02-05 21:08 UTC
Labels: bug

**Comment by mvalois** [comment] 2024-02-06 13:11
Yes, the problem went away with your fix. Thank you =)
