### ISSUE TITLE
Changing data in SSO provider resets the entire configuration object

### ISSUE THREAD

**Issue by Spiritreader** [go-vikunja/api#108] opened 2024-01-27 22:19 UTC
### Description

Hello!

When a user changes their e-mail address in the SSO provider, the respective database object in vikunja gets updated as expected. (Checked with pgadmin by querying the user table before and after)
However, all other user configurable settings are reset to default in the process.
For example avatar configuration, visibility options, week start date etc.
 
Ideally, it would be awesome if only the fields are changed that are actually updated via the SSO provider.
Not a big issue in any way, just stumbled across this when I updated my e-mail in authentik.

### Vikunja Frontend Version

0.22.0

### Vikunja API Version

v0.22.0

### Browser and version

Firefox 123.03b

### Can you reproduce the bug on the Vikunja demo site?

No

**Comment by kolaente** [comment] 2024-01-27 22:22
Duplicate of https://github.com/go-vikunja/api/issues/107

**Closed** 2024-01-27 22:22 UTC
